import { purgeCss } from 'vite-plugin-tailwind-purgecss';
import { sveltekit } from '@sveltejs/kit/vite';
import { defineConfig } from 'vite';

export default defineConfig({
  plugins: [sveltekit(), purgeCss()],
  ssr: {
    noExternal: [
      '@tsparticles/basic',
      '@tsparticles/engine',
      '@tsparticles/interaction-external-attract',
      '@tsparticles/interaction-external-bounce',
      '@tsparticles/interaction-external-bubble',
      '@tsparticles/interaction-external-connect',
      '@tsparticles/interaction-external-grab',
      '@tsparticles/interaction-external-pause',
      '@tsparticles/interaction-external-push',
      '@tsparticles/interaction-external-remove',
      '@tsparticles/interaction-external-repulse',
      '@tsparticles/interaction-external-slow',
      '@tsparticles/interaction-external-trail',
      '@tsparticles/interaction-particles-attract',
      '@tsparticles/interaction-particles-collisions',
      '@tsparticles/interaction-particles-links',
      '@tsparticles/move-base',
      '@tsparticles/move-parallax',
      '@tsparticles/plugin-absorbers',
      '@tsparticles/plugin-easing-quad',
      '@tsparticles/plugin-emitters',
      '@tsparticles/plugin-emitters-shape-circle',
      '@tsparticles/plugin-emitters-shape-square',
      '@tsparticles/shape-circle',
      '@tsparticles/shape-emoji',
      '@tsparticles/shape-image',
      '@tsparticles/shape-line',
      '@tsparticles/shape-polygon',
      '@tsparticles/shape-square',
      '@tsparticles/shape-star',
      '@tsparticles/shape-text',
      '@tsparticles/slim',
      '@tsparticles/svelte',
      '@tsparticles/updater-color',
      '@tsparticles/updater-destroy',
      '@tsparticles/updater-life',
      '@tsparticles/updater-opacity',
      '@tsparticles/updater-out-modes',
      '@tsparticles/updater-roll',
      '@tsparticles/updater-rotate',
      '@tsparticles/updater-size',
      '@tsparticles/updater-stroke-color',
      '@tsparticles/updater-tilt',
      '@tsparticles/updater-twinkle',
      '@tsparticles/updater-wobble',
    ],
  },
});
